spring:
  application:
    name: hello-spring-cloud-webclient-dept-feign
  zipkin:
    base-url: http://localhost:9411  
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
server:
  port: 8766
#feign中自带熔断器，默认是关闭的，可以在全局配置文件中开启
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7001/eureka/

